### ISSUE TITLE
receive a "Cannot find module 'webpack-cli/package.json'" error message

### ISSUE THREAD

**Issue by rpcorr** [coveo/search-ui-seed#33]
Hello @olamothe @francoislg @jdevost @dms1lva @ekomisarenko @davaucl @fbeaudoincoveo @dlutzCoveo ,

I am using this repo for a Coveo Level-up course.  I am following the steps, all goes well until  I reach the stage to **run watch**, I receive a notification that CLI for webpack must be installed.  After clicking "yes" to continue, I see a "cannot find module 'webpack-cli/package.json'" error message.

Looking in my package.json file, I see the webpack-cli version ^4.10.0 is present.  Do you have any idea how to correct this so I will no longer receive an error and can continue with my Coveo Level-up course?

Cheers

**Comment by jpmarceau** [comment]
Dear @rpcorr ,
First, apologies for the delayed response. With changes in the teams and vacation season, it took a while before I the issue reached me 😅
I just merged [a PR](https://github.com/coveo/search-ui-seed/pull/34) that should fix your issue. Please sync your branch with master, make sure you're using node 16, and then retry the instructions. Let me know if you still face the same issue 😄

**Comment by rpcorr** [comment]
@jpmarceau ,

No problem. Thanks for your reply.  I synced my branch with master and followed the instructions again.  When I type in "npm run watch", I no longer get cannot find webpack module error  message and can view the page at localhost:3000 as mentioned in the tutorial.

Cheers
